### ISSUE TITLE
problem calling the fuction

### ISSUE THREAD

**Issue by flopflip** [mlampros/RGF#1]
trying the example from the vignette (install is fine), I get:

 RGF_class = RGF_Classifier$new(max_leaf = 50)
Error in .subset2(public_bind_env, "initialize")(...) : 
  attempt to apply non-function

--- on the other hand
RGF_class = RGF_Classifier$new

throws no error

**Comment by mlampros** [comment]
@flopflip,

the  *.... attempt to apply non-function .....* error mostly occurs when one (or all) python module(s) is (are) not properly installed. The RGF package uses the [reticulate](https://github.com/rstudio/reticulate) package for the interface between Python and R. There is a [similar issue](https://github.com/mlampros/fuzzywuzzyR/issues/1) in another of my packages (fuzzywuzzyR) which might be helpful to you.

**Comment by flopflip** [comment]
Thank you!

install seems ok though - which python modules are required other than 'sklearn' ?:

> reticulate::py_discover_config(required_module = 'sklearn')
python:         /usr/bin/python
libpython:      /usr/lib/python2.7/config-x86_64-linux-gnu/libpython2.7.so
pythonhome:     /usr:/usr
version:        2.7.12 (default, Dec  4 2017, 14:50:18)  [GCC 5.4.0 20160609]
numpy:          /usr/local/lib/python2.7/dist-packages/numpy
numpy_version:  1.14.3
sklearn:        /usr/local/lib/python2.7/dist-packages/sklearn




________________________________________

**Comment by flopflip** [comment]
the solution:
change the permissions of /tmp/rgf

**Comment by mlampros** [comment]
@flopflip I'm glad you made it work. 

I close the issue for now, feel free to reopen it.

**Comment by skwskwskwskw** [comment]
Sorry - I still not able to get it works? Facing the same issue and I don't understand what's meant by changing the permissions as suggested by @flopflip

**Comment by skwskwskwskw** [comment]
Attached is the input from reticulate package. Kindly help. Thanks.

![image](https://user-images.githubusercontent.com/7208012/41811081-4cd04380-773b-11e8-89c1-ffbff088244a.png)

**Comment by mlampros** [comment]
@skw1990 I'm sorry for the late reply,

from the attached image I assume you are working on a Windows operating system (OS), whereas @flopflip works on a Unix OS (Linux or Macintosh). Therefore the 'permission changing' solution does not apply to you.  

I included details on how to install the package on windows on the [README.md](https://github.com/mlampros/RGF/blob/master/README.md) file, however you should know that ,

* on windows the user can take advantage of the RGF package currently only from within the command prompt (console or cmd) 
* the installation is somehow cumbersome on Windows (it took me a while to make it work on my windows machine)

You could also have a look to the rgf_python [README.rst](https://github.com/RGF-team/rgf/blob/master/Readme.rst) file which has more up-to-dated installation instructions. It also has a [docker-file](https://github.com/RGF-team/rgf/blob/master/docker/Dockerfile) if you are familiar with docker installations.

 As you already know the RGF R package relies on the rgf_python package, and uses the [reticulate](https://github.com/rstudio/reticulate) package for the interface between Python and R.

**Comment by skwskwskwskw** [comment]
That's not late at all. Yes, I am working on Win10 pc. I see so, you suggest to use it in python only? On the side not, may I know if there's tutorial via cmd? Thanks.

**Comment by mlampros** [comment]
@skw1990 ,

the only difference (I personally see) when working on cmd in comparison to an R Gui is code auto completion and the fact that you have to copy-paste small chunks of code, otherwise you can call the RGF package from cmd in the same way as in an R Gui.

As I explained in the[ README.md ](https://github.com/mlampros/RGF/blob/master/README.md) you have to first locate where R is installed, for instance in my WIndows machine R is located in C:\Program Files\R\R-3.4.0\bin\x64\R. Then, by opening a command prompt (console) and giving (for instance in my case),

```R

cd C:\Program Files\R\R-3.4.0\bin\x64\

R

library(RGF)

```

you can proceed working with the RGF package.

**Comment by skwskwskwskw** [comment]
Alright. Thank you very much.
